[package]
name = "jackmute_1lt"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.10.0"
config_1lt = { git = "https://github.com/1LtFord/1lt_config.git" }