name: Build

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: install jack
      run: |
        sudo apt-get update
        sudo apt-get install libjack-jackd2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
